*       common6.
*       -------
*
      INCLUDE 'params.h'
      IMPLICIT REAL*8  (A-H,O-Z)
      REAL*8  MP,MP0,MPDOT
*
      COMMON/NBODY/  X(3,NMAX),X0(3,NMAX),X0DOT(3,NMAX),F(3,NMAX),
     &               FDOT(3,NMAX),BODY(NMAX),RS(NMAX),XDOT(3,NMAX),
     &               FI(3,NMAX),D1(3,NMAX),D2(3,NMAX),D3(3,NMAX),
     &               FR(3,NMAX),D1R(3,NMAX),D2R(3,NMAX),D3R(3,NMAX),
     &               STEP(NMAX),T0(NMAX),STEPR(NMAX),T0R(NMAX)
*
      COMMON/PAIRS/  HT,U(4,KMAX),U0(4,KMAX),UDOT(4,KMAX),FU(4,KMAX),
     &               FUDOT(4,KMAX),FUDOT2(4,KMAX),FUDOT3(4,KMAX),
     &               H(KMAX),HDOT(KMAX),HDOT2(KMAX),HDOT3(KMAX),
     &               HDOT4(KMAX),DTAU(KMAX),TDOT2(KMAX),TDOT3(KMAX),
     &               R(KMAX),R0(KMAX),GAMMA(KMAX),SF(7,KMAX),H0(KMAX),
     &               FP0(4,KMAX),FD0(4,KMAX),TBLIST,DTB,KBLIST(KMAX),
     &               NNTB
*
      COMMON/NAMES/  N,NTOT,NPAIRS,NNBMAX,NCRIT,NFIX,NMERGE,NSUB,NCH,
     &               IPHASE,IFIRST,ICOMP,JCOMP,ICLOSE,JCLOSE,KSPAIR,
     &               NRUN,MODEL,NC,NZERO,NBIN0,IDUM1,NAME0,NHI0,KZ(40),
     &               KVEC(2*KMAX),LISTR(MLR),LISTD(MLD),LISTV(MLV),
     &               KSLOW(KMAX),NAME(NMAX),LIST(LMAX,NMAX),NCHAOS
*
      COMMON/COUNTS/ NSTEPI,NSTEPR,NSTEPU,NNPRED,NBCORR,NBFULL,NBVOID,
     &               NRCONV,NBSMIN,NLSMIN,NBDIS,NBDIS2,NCMDER,NBDER,
     &               NFAST,NBFAST,NBLOCK,NBPRED,NICONV,NCHAIN,NSTEPC,
     &               NKSTRY,NKSREG,NKSHYP,NKSPER,NPRECT,NEWKS,NKSMOD,
     &               NTTRY,NTRIP,NQUAD,NMERG,NSTEPT,NSTEPQ,NDISS,NTIDE,
     &               NCOLL,NSYNC,NSESC,NBESC,NMESC,NTIMER,NSTEPS,NPRINT,
     &               NDUMP,NBPREV,NPOP(10),JCMAX,NEWHI,NSTEPB,NBFLUX,
     &               NMTRY,NWARN,NIRECT,NURECT,NBRECT,NRRECT,NOFL(2),
     &               NBZERO,KSMAG
*
      COMMON/PARAMS/ CPU,ETAI,ETAR,DTADJ,DELTAT,TCRIT,QE,RBAR,ZMBAR,
     &               DTMIN,RMIN,ETAU,CMSEP2,ECLOSE,GMIN,GMAX,ETA0,
     &               TWOPI,ONE3,ONE6,ONE9,ONE12,TCR0,TRH,BODYM,BODY1,
     &               SMIN,RMIN2,RMIN22,STEPJ,ALPHA,ZNBMIN,ZNBMAX,EBH,
     &               TADJ,TNEXT,CPU0,CPUTOT,SMAX,TINY,DUMMY(2),
     &               TIME,ZMASS,RSCALE,TCR,TRC,BE(3),CMR(4),CMRDOT(4),
     &               ZKIN,POT,EBIN,EBIN0,ESUB,EMERGE,ECOLL,EDISS,ESYNC,
     &               E(12),ERROR,ERRTOT,DETOT,ETCORR,AZ,PCRIT,EBCH0,
     &               RTIDE,TSCALE,TIDAL(4),ETIDE,RSFAC,RSPH2,BETA2,
     &               RC,RC2,RC2IN,VC,ZMC,RDENS(3),RHOD,RHOM,RSMIN,RMAX,
     &               DMIN1,DMIN2,DMIN3,DMIN4,DMINC,SBCOLL,BBCOLL,CHCOLL,
     &               DELTAS,ORBITS(9),GPRINT(9),TLASTT,TLASTS,TLASTB(9),
     &               TDUMP,SCOEFF(12),TOFF,TTOT,EBESC,EMESC,ESESC,
     &               CLIGHT,RZ,EGRAV
*
      COMMON/STARS/  EPOCH0,ZMRG,ZMHE,ZMRS,ZMWD,ZMSN,ZMNH,ZMBH,ZMDOT,
     &               AU,PC,GM,DAYS,YRS,SU,SMU,RAU,TSTAR,VSTAR,STEPX,
     &               TMDOT,TPHYS,TURN,EMDOT,ECDOT,EKICK,TPLOT,DTPLOT,
     &               XHYD,YHEL,ZMET,ZPARS(20),SPNFAC,
     &               RADIUS(NMAX),TEV(NMAX),TEV0(NMAX),BODY0(NMAX),
     &               EPOCH(NMAX),SPIN(NMAX),XSTAR(NMAX),ZLMSTY(NMAX),
     &               IQCOLL,NAS,NBH,NBKICK,NBR,NBRK,NBS,NCHA,NCIRC,
     &               NCOAL,NCONT,NDD,NEMOD,NGB,NGLOB,NGLOB0,NHE,NHG,NHI,
     &               NHYP,NKICK,NMDOT,NMS,NNH,NRG,NRO,NROCHE,NRS,NRSAVE, 
     &               NSHOCK,NSLP,NSN,NSP,NSPIR,INSTAB,NTZ,NWD,
     &               ITYPE(5),KSAVE(4),KSTAR(NMAX),
     &               KTYPE(0:14,0:14),NEINT,IBLUE,NBH0,NGDUM(7),
     &               ITAIL0,NTAIL,NTTOT,NSTAIL,N1
*
      COMMON/PLPOT/  MP,AP2,VIR,MP0,MPDOT,TDELAY,RTIDE0,QVIR,PLDUM(4)
*
      COMMON/HERMIT/ FIDOT(3,NMAX),D0(3,NMAX),FRDOT(3,NMAX),D0R(3,NMAX)
*
      COMMON/BLOCKS/ TPREV,TBLOCK,DTK(40),TNEW(NMAX)
*
      COMMON/LISTS/  ILIST(NMAX),JLIST(NMAX),JPERT(5*LMAX)
